# Generated by Django 3.2.14 on 2022-10-30 16:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import python_evaluator.models.environment
import python_evaluator.models.environment_file
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('requirements_file', models.FileField(upload_to=python_evaluator.models.environment.upload_environment, validators=[django.core.validators.FileExtensionValidator(['txt'])])),
                ('status', django_mysql.models.EnumField(choices=[('queued', 'Queued'), ('building', 'Building'), ('completed', 'Completed'), ('error', 'Error')], default='queued')),
                ('python_version', django_mysql.models.EnumField(choices=[('3.6', 'Python36'), ('3.7', 'Python37'), ('3.8', 'Python38')])),
                ('slug', models.UUIDField(default=uuid.uuid4)),
                ('docker_image', models.CharField(blank=True, max_length=512, null=True)),
                ('build_logs', models.TextField(blank=True, null=True)),
                ('build_commands', models.TextField(blank=True, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'python_environments',
            },
        ),
        migrations.CreateModel(
            name='PythonSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('output', models.TextField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('slug', models.UUIDField(default=uuid.uuid4)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='python_evaluator.pythonenvironment')),
            ],
            options={
                'db_table': 'python_submissions',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=python_evaluator.models.environment_file.upload_environment_file)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_evaluator.pythonenvironment')),
            ],
            options={
                'db_table': 'environment_files',
            },
        ),
    ]
