# Generated by Django 3.2 on 2022-09-24 18:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import python_evaluator.models.environment
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('requirements_file', models.FileField(upload_to=python_evaluator.models.environment.upload_environment, validators=[django.core.validators.FileExtensionValidator(['txt'])])),
                ('slug', models.UUIDField(default=uuid.uuid4)),
                ('docker_image', models.CharField(blank=True, max_length=512, null=True)),
                ('build_logs', models.TextField(blank=True, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'python_environments',
            },
        ),
        migrations.CreateModel(
            name='PythonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('expected_output', models.FileField(blank=True, null=True, upload_to='')),
                ('slug', models.UUIDField(default=uuid.uuid4)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='python_evaluator.pythonenvironment')),
            ],
            options={
                'db_table': 'python_questions',
            },
        ),
        migrations.CreateModel(
            name='PythonQuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('output', models.TextField()),
                ('time', models.IntegerField()),
                ('python_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_evaluator.pythonquestion')),
            ],
            options={
                'db_table': 'python_question_submissions',
            },
        ),
    ]
