# Generated by Django 3.2 on 2022-09-25 09:05

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('python_evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonenvironment',
            name='python_version',
            field=django_mysql.models.EnumField(choices=[('3.6', 'Python36'), ('3.7', 'Python37'), ('3.8', 'Python38')]),
        ),
    ]
