# Generated by Django 3.2.14 on 2022-10-12 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('python_evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonsubmission',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
