# Generated by Django 3.2 on 2022-09-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_evaluator', '0002_alter_pythonenvironment_python_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonquestionsubmission',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pythonquestionsubmission',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
